
import React, { useState, useEffect } from 'react'
const API = '/api'
export default function App(){
  const [tab,setTab]=useState('dashboard')
  const [clients,setClients]=useState([])
  const [blueprints,setBlueprints]=useState([])
  const [form,setForm]=useState({name:'',email:'',company:'',service:'AI System Build',source:'tally',blueprintId:'saas-supabase',discoveryData:{}})
  const [selected,setSelected]=useState(null)
  const [logs,setLogs]=useState([])
  const [scaffoldLog,setScaffoldLog]=useState([])
  const [repos,setRepos]=useState([])
  const [proposals,setProposals]=useState([])
  const [forgeNodes,setForgeNodes]=useState([{id:'1',type:'Trigger',label:'Tally Form'}])
  const [payStatus,setPayStatus]=useState('unpaid')

  const fetchAll=async()=>{
    try{
      const [c,b,r,p]=await Promise.all([
        fetch(`${API}/clients`).then(r=>r.json()).catch(()=>[]),
        fetch(`${API}/blueprints`).then(r=>r.json()).catch(()=>[]),
        fetch(`${API}/repos`).then(r=>r.json()).catch(()=>[]),
        fetch(`${API}/proposals`).then(r=>r.json()).catch(()=>[])
      ])
      setClients(c); setBlueprints(b); setRepos(r); setProposals(p);
      if(c.length&&!selected) setSelected(c[0])
    }catch{}
  }
  useEffect(()=>{fetchAll()},[])

  const submitIntake=async(e)=>{
    e.preventDefault()
    const res=await fetch(`${API}/intake`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)})
    const data=await res.json()
    setSelected(data.client); setLogs([`Zapier webhook: ${data.zapierEvent}`, `Blueprint matched: ${data.blueprint.name}`]); setTab('builder'); fetchAll()
  }

  const scaffold=async()=>{
    setScaffoldLog(['> Analyzing discovery...','> Generating file tree via OpenRouter...'])
    setTimeout(()=>setScaffoldLog(s=>[...s,'> Creating GitHub repo from template...']),800)
    setTimeout(()=>setScaffoldLog(s=>[...s,'> Pushing files...']),1500)
    setTimeout(()=>setScaffoldLog(s=>[...s,'> Deploying to Render...']),2200)
    const prompt = document.getElementById('buildPrompt')?.value || 'Build full system'
    const res=await fetch(`${API}/builder/scaffold`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:selected?.id||clients[0]?.id, prompt, blueprintId:form.blueprintId})})
    const repo=await res.json()
    setTimeout(()=>{ setScaffoldLog(s=>[...s,`> DONE: ${repo.liveUrl}`]); fetchAll(); },2600)
  }

  const dynamicFields=()=>{
    const s=form.service
    if(s.includes('Custom')||s.includes('SaaS')) return [{k:'appPurpose',label:'What should the app do?'},{k:'users',label:'Who are the users?'},{k:'data',label:'What data does it need?'}]
    if(s.includes('WhatsApp')) return [{k:'businessType',label:'Business type?'},{k:'tone',label:'Bot tone (friendly/professional)'},{k:'escalation',label:'When to escalate to human?'}]
    if(s.includes('AI System')) return [{k:'useCase',label:'Use case?'},{k:'dataSources',label:'Data sources?'},{k:'integrations',label:'Integrations (Notion, Gmail etc)?'}]
    return [{k:'goal',label:'Main goal?'}]
  }

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white font-mono">
      <header className="border-b border-white/10 p-4 flex justify-between items-center sticky top-0 bg-[#0a0a0a] z-10">
        <div className="flex gap-3 items-center"><div className="w-8 h-8 bg-[#ccff00] rounded flex items-center justify-center text-black font-black">ITG</div><span className="font-bold">ITG FACTORY v2</span><span className="text-[10px] px-2 py-1 bg-[#ccff00] text-black rounded font-bold">APP FACTORY • READY TO MARKET</span></div>
        <div className="text-xs text-white/40">{clients.length} clients • {repos.length} apps deployed • Paystack + GitHub + Render</div>
      </header>
      <nav className="flex gap-1 p-3 border-b border-white/10 overflow-auto">
        {['dashboard','intake','builder','forge','proposals','portal','delivery','growth'].map(t=><button key={t} onClick={()=>setTab(t)} className={`px-3 py-2 rounded text-[11px] uppercase tracking-widest whitespace-nowrap ${tab===t?'bg-[#ccff00] text-black font-bold':'bg-white/5 text-white/60'}`}>{t}</button>)}
      </nav>
      <main className="p-6 max-w-7xl mx-auto">
        {tab==='dashboard'&&<div className="grid md:grid-cols-4 gap-4"><div className="bg-white/[0.03] border border-white/10 rounded-xl p-6"><div className="text-xs text-white/40">Active Clients</div><div className="text-3xl font-bold mt-2">{clients.length}</div></div><div className="bg-white/[0.03] border border-white/10 rounded-xl p-6"><div className="text-xs text-white/40">Apps Deployed</div><div className="text-3xl font-bold mt-2">{repos.length}</div><div className="text-xs text-[#ccff00] mt-1">Live on Render</div></div><div className="bg-white/[0.03] border border-white/10 rounded-xl p-6"><div className="text-xs text-white/40">Revenue Pipeline</div><div className="text-3xl font-bold mt-2">${clients.length*1800}</div><div className="text-xs text-white/40">Paystack ready</div></div><div className="bg-[#ccff00] rounded-xl p-6 text-black"><div className="text-xs font-bold">FREE STACK STATUS</div><div className="text-xs mt-2">✓ OpenRouter ✓ Supabase ✓ GitHub ✓ Render ✓ Paystack ✓ WhatsApp API</div><button onClick={fetchAll} className="mt-3 bg-black text-[#ccff00] px-3 py-1 rounded text-xs">Refresh</button></div><div className="md:col-span-4 bg-black border border-white/10 rounded-xl p-6"><h3 className="font-bold mb-3">Recent Factory Activity</h3>{clients.slice(-5).map(c=><div key={c.id} className="text-xs py-2 border-b border-white/5 flex justify-between"><span>{c.name} - {c.service} - {c.status}</span><span className="text-white/40">{new Date(c.createdAt).toLocaleString()}</span></div>)}</div></div>}

        {tab==='intake'&&<div className="grid md:grid-cols-2 gap-6"><div className="bg-white/[0.03] border border-white/10 rounded-xl p-6"><h2 className="font-bold mb-4">Intake+ Dynamic (Tally / WhatsApp)</h2><form onSubmit={submitIntake} className="space-y-3"><input className="w-full bg-black border border-white/10 rounded p-3 text-sm" placeholder="Client Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input className="w-full bg-black border border-white/10 rounded p-3 text-sm" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input className="w-full bg-black border border-white/10 rounded p-3 text-sm" placeholder="Company" value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/><select className="w-full bg-black border border-white/10 rounded p-3 text-sm" value={form.service} onChange={e=>setForm({...form,service:e.target.value})}><option>AI System Build</option><option>Custom SaaS App</option><option>WhatsApp Bot</option><option>Automation Setup</option><option>AI Training</option><option>Prompt Engineering Pack</option></select><select className="w-full bg-black border border-white/10 rounded p-3 text-sm" value={form.blueprintId} onChange={e=>setForm({...form,blueprintId:e.target.value})}>{blueprints.map(b=><option key={b.id} value={b.id}>{b.name} - ${b.priceBase}</option>)}</select><div className="space-y-2 pt-2 border-t border-white/10 mt-3"><div className="text-xs text-[#ccff00]">Dynamic Discovery for {form.service}</div>{dynamicFields().map(f=><input key={f.k} className="w-full bg-black border border-white/10 rounded p-3 text-sm" placeholder={f.label} onChange={e=>setForm({...form,discoveryData:{...form.discoveryData,[f.k]:e.target.value}})} />)}</div><button className="w-full bg-[#ccff00] text-black font-bold py-3 rounded">Create Client → Trigger Factory</button></form></div><div className="bg-black border border-white/10 rounded-xl p-6"><h3 className="text-xs text-white/40">BLUEPRINT REGISTRY (Notion/Airtable)</h3><div className="mt-3 space-y-2">{blueprints.map(b=><div key={b.id} className="p-3 bg-white/5 rounded text-xs"><div className="font-bold">{b.name}</div><div className="text-white/40 text-[11px]">{b.stack} | ${b.priceBase} base</div><div className="text-white/60 mt-1">{b.description}</div></div>)}</div></div></div>}

        {tab==='builder'&&<div className="grid md:grid-cols-3 gap-6"><div className="bg-white/[0.03] border border-white/10 rounded-xl p-6"><h3 className="font-bold text-sm">Prompt-to-App Generator</h3><textarea id="buildPrompt" className="w-full mt-3 bg-black border border-white/10 rounded p-3 text-xs h-32" placeholder="Describe app for client: e.g. Build a real estate WhatsApp bot that qualifies leads, syncs to Notion, sends Paystack link..."></textarea><button onClick={scaffold} className="w-full mt-3 bg-[#ccff00] text-black font-bold py-3 rounded text-sm">Scaffold App → GitHub → Render</button><div className="mt-4 bg-black p-3 rounded text-[11px] font-mono text-[#ccff00] min-h-[120px]">{scaffoldLog.map((l,i)=><div key={i}>{l}</div>)}{scaffoldLog.length===0&&<span className="text-white/20">Logs will appear here...</span>}</div></div><div className="bg-white/[0.03] border border-white/10 rounded-xl p-6"><h3 className="text-xs text-white/40">DEPLOYED REPOS</h3>{repos.slice(-5).reverse().map(r=><div key={r.id} className="mt-3 p-3 bg-black rounded border border-white/10 text-xs"><div className="font-bold">{r.name}</div><div className="text-[#ccff00] truncate">{r.liveUrl}</div><div className="text-white/40 mt-1">{r.files.slice(0,3).join(' • ')}</div><button className="mt-2 bg-white/10 px-2 py-1 rounded text-[10px]">Open Live URL</button></div>)}</div><div className="bg-black border border-white/10 rounded-xl p-6"><div className="flex justify-between items-center"><h3 className="text-xs text-white/40">AGENT DECISION LOG</h3><button onClick={async()=>{const id=selected?.id||clients[0]?.id; if(!id)return alert('Create client first'); const res=await fetch(`${API}/agent/decide`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:id})}); const data=await res.json(); setLogs(data.logs||[]);}} className="bg-white/10 text-[10px] px-2 py-1 rounded">Run Agent Decision</button></div><pre className="mt-3 text-[11px] text-[#ccff00] whitespace-pre-wrap">{logs.join('\n')||'Run intake or click "Run Agent Decision"'}</pre>{selected&&<div className="mt-4 p-3 bg-white/5 rounded text-xs"><div>Selected: {selected.name}</div><div className="text-white/40">Status: {selected.status} | Paid: {selected.paymentStatus}</div></div>}</div></div>}

        {tab==='forge'&&<div className="bg-white/[0.03] border border-white/10 rounded-xl p-6"><h2 className="font-bold">Agent Forge - Visual Builder</h2><div className="flex gap-2 mt-4 flex-wrap"><button onClick={()=>setForgeNodes([...forgeNodes,{id:Date.now().toString(),type:'Trigger',label:'WhatsApp'}])} className="bg-white/10 px-3 py-2 rounded text-xs">+ Trigger</button><button onClick={()=>setForgeNodes([...forgeNodes,{id:Date.now().toString(),type:'LLM',label:'mistral-7b-free'}])} className="bg-white/10 px-3 py-2 rounded text-xs">+ LLM</button><button onClick={()=>setForgeNodes([...forgeNodes,{id:Date.now().toString(),type:'Tool',label:'Notion'}])} className="bg-white/10 px-3 py-2 rounded text-xs">+ Tool (Notion/Gmail)</button><button onClick={()=>setForgeNodes([...forgeNodes,{id:Date.now().toString(),type:'Action',label:'Send Email'}])} className="bg-white/10 px-3 py-2 rounded text-xs">+ Action</button></div><div className="mt-6 bg-black rounded-xl p-6 min-h-[200px] border border-white/10 flex gap-3 flex-wrap items-start">{forgeNodes.map(n=><div key={n.id} className={`px-4 py-3 rounded border text-xs ${n.type==='Trigger'?'border-blue-500 bg-blue-500/10':n.type==='LLM'?'border-[#ccff00] bg-[#ccff00]/10 text-[#ccff00]':n.type==='Tool'?'border-purple-500 bg-purple-500/10':'border-white/20 bg-white/5'}`}><div className="text-[10px] opacity-60">{n.type}</div><div className="font-bold">{n.label}</div></div>)}<div className="w-full mt-4 text-[10px] text-white/20">→ Flow: {forgeNodes.map(n=>n.type).join(' → ')}</div></div><div className="mt-4 grid md:grid-cols-2 gap-4"><pre className="bg-black p-4 rounded text-[11px] overflow-auto">{JSON.stringify({agent:{model:'mistralai/mistral-7b-instruct:free',nodes:forgeNodes, openRouterBase:'https://openrouter.ai/api/v1'}},null,2)}</pre><div className="bg-[#ccff00] p-4 rounded text-black text-xs"><b>LangChain Export</b><br/>This JSON is your Vercel/Render function. Paste into server/langchain-agent.js and it runs.<br/><button className="mt-3 bg-black text-[#ccff00] px-3 py-2 rounded text-xs">Export to Render</button></div></div></div>}

        {tab==='portal'&&<div className="grid md:grid-cols-2 gap-6"><div className="bg-white rounded-xl p-6 text-black"><div className="flex justify-between"><span className="font-bold">Client Portal Preview /c/{selected?.id?.slice(-6)||'demo'}</span><span className="text-xs px-2 py-1 bg-black text-white rounded">{selected?.status||'proposal_sent'}</span></div><div className="mt-6"><h3 className="font-bold text-lg">{selected?.name||'Demo Client'} - {selected?.service||'AI System Build'}</h3><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between p-2 bg-black/5 rounded"><span>Proposal</span><span>✓ Sent</span></div><div className="flex justify-between p-2 bg-black/5 rounded"><span>GitHub Repo</span><span className="text-blue-600">{repos[0]?.url?.slice(0,30)||'pending...'}</span></div><div className="flex justify-between p-2 bg-black/5 rounded"><span>Live App</span><span className="text-green-600">{repos[0]?.liveUrl||'deploying...'}</span></div><div className="flex justify-between p-2 bg-black/5 rounded"><span>Prompt Library</span><span>24 prompts</span></div></div><div className="mt-6 p-4 bg-[#ccff00] rounded"><div className="font-bold text-sm">Pay with Paystack</div><div className="text-xs">Amount: $1,800 • ZAR ~R33,000</div><button onClick={async()=>{const r=await fetch(`${API}/paystack/mock-confirm`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:selected?.id||clients[0]?.id})}); setPayStatus('paid'); fetchAll();}} className="w-full mt-2 bg-black text-white py-2 rounded text-sm">{payStatus==='paid'?'✓ Paid':'Pay Now (Paystack)'}</button></div></div></div><div className="bg-white/[0.03] border border-white/10 rounded-xl p-6"><h3 className="font-bold text-sm">White-Label Settings (Resell ITG Flow)</h3><input className="w-full mt-3 bg-black border border-white/10 rounded p-3 text-sm" placeholder="Your agency name (e.g. ITG)"/><input className="w-full mt-2 bg-black border border-white/10 rounded p-3 text-sm" placeholder="Logo URL"/><input className="w-full mt-2 bg-black border border-white/10 rounded p-3 text-sm" placeholder="Primary color #ccff00"/><div className="mt-4 text-xs text-white/40">Toggle this and your client portal becomes theirs - you can sell ITG Factory to other consultants for $199/mo.</div><button className="w-full mt-3 bg-white text-black py-2 rounded text-sm font-bold">Save White-Label</button><div className="mt-6 p-3 bg-black rounded text-xs"><b>Marketing copy ready:</b><br/>"We build any AI system in 7 days - live URL, GitHub repo, training included. Pay with Paystack. Track progress in your portal."</div></div></div>}

        {tab==='proposals'&&<div className="bg-white/[0.03] border border-white/10 rounded-xl p-6"><h2 className="font-bold">Proposals (Google Docs + Gmail)</h2><p className="text-xs text-white/40 mt-1">Dynamic pricing: base + complexity from discovery data</p><button onClick={async()=>{const id=selected?.id||clients[0]?.id; if(!id)return alert('Create client first'); const r=await fetch(`${API}/proposals/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:id})}); const d=await r.json(); alert(`Proposal $${d.price} sent to ${d.clientName}`); fetchAll();}} className="mt-4 bg-[#ccff00] text-black px-4 py-2 rounded text-sm font-bold">Generate Proposal_Generator.md</button><div className="mt-6 space-y-4">{proposals.map(p=><div key={p.id} className="p-4 bg-black rounded border border-white/10 text-xs"><div className="flex justify-between items-center font-bold text-sm"><span>Proposal for {p.clientName}</span><span className="text-[#ccff00]">${p.price}</span></div><pre className="mt-3 text-white/70 whitespace-pre-wrap font-mono text-[11px] bg-white/5 p-3 rounded">{p.markdown}</pre></div>)}</div></div>}

        {tab==='delivery'&&<div className="bg-white/[0.03] border border-white/10 rounded-xl p-6"><h2 className="font-bold">Delivery Factory - Kanban</h2><div className="grid md:grid-cols-4 gap-4 mt-4">{['new','building','qa','delivered'].map(stage=><div key={stage} className="bg-black rounded-xl p-4 border border-white/10"><div className="text-xs uppercase tracking-widest text-white/40">{stage}</div><div className="mt-3 space-y-2">{clients.filter(c=> (stage==='new'&&['new','proposal_sent','paid'].includes(c.status)) || c.status===stage || (stage==='building'&&c.status==='onboarding') ).map(c=><div key={c.id} className="p-3 bg-white/5 rounded text-xs"><div className="font-bold">{c.name}</div><div className="text-white/40">{c.service}</div><button onClick={async()=>{await fetch(`${API}/delivery/update`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:c.id,stage:stage==='new'?'building':stage==='building'?'qa':'delivered',note:`Moved to ${stage}`})}); fetchAll();}} className="mt-2 bg-white/10 px-2 py-1 rounded text-[10px]">→ Next</button></div>)}</div></div>)}</div></div>}

        {tab==='growth'&&<div className="grid md:grid-cols-2 gap-6"><div className="bg-white/[0.03] border border-white/10 rounded-xl p-6"><h3 className="font-bold">Prompt Pack Marketplace (Upsell)</h3><div className="mt-3 space-y-2 text-xs"><div className="p-3 bg-black rounded border border-white/10"><b>Real Estate - 50 prompts</b> - R2,500 - 12 uses</div><div className="p-3 bg-black rounded border border-white/10"><b>WhatsApp Sales - 30 prompts</b> - R1,200 - 8 uses</div><div className="p-3 bg-black rounded border border-white/10"><b>SaaS Onboarding - 40 prompts</b> - R1,800 - 5 uses</div></div></div><div className="bg-[#ccff00] rounded-xl p-6 text-black"><h3 className="font-bold">Retainer Automator</h3><div className="text-xs mt-2">After delivery, auto-send monthly optimization report via Gmail. Turns one-off $2.5k into $300/mo retainer.</div><div className="mt-3 flex gap-2"><span className="px-2 py-1 bg-black text-[#ccff00] rounded text-xs">✓ Auto-report ON</span><span className="px-2 py-1 bg-black/10 rounded text-xs">UptimeRobot ping every 15m</span></div><div className="mt-4 bg-black text-[#ccff00] p-3 rounded text-xs">Marketing angle: "We don't just build, we run it."</div></div></div>}
      </main>
    </div>
  )
}
