
const express = require('express');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const app = express();
const PORT = process.env.PORT || 10000;

app.use(cors());
app.use(express.json({ limit: '10mb' }));

// DB - In memory, swap to Supabase via SUPABASE_URL env
let db = {
  clients: [],
  proposals: [],
  tasks: [],
  deliveries: [],
  testimonials: [],
  promptPacks: [],
  repos: [],
  blueprints: [
    { id: 'saas-supabase', name: 'SaaS Starter - Supabase + Next.js', stack: 'nextjs, supabase, tailwind', priceBase: 2500, githubTemplate: 'https://github.com/org/saas-supabase-template', description: 'Auth, DB, billing ready' },
    { id: 'whatsapp-bot', name: 'WhatsApp Bot - Baileys + OpenAI', stack: 'node, baileys, openai', priceBase: 1200, githubTemplate: 'https://github.com/org/wa-bot-template', description: 'Auto-replies, escalation, CRM sync' },
    { id: 'langchain-agent', name: 'LangChain Agent - OpenRouter', stack: 'langchain, openrouter, vercel', priceBase: 1800, githubTemplate: 'https://github.com/org/langchain-agent-template', description: 'Your original ITG agent, now reusable' },
    { id: 'notion-crm', name: 'Notion CRM Automation', stack: 'zapier, notion, gmail', priceBase: 800, githubTemplate: 'https://github.com/org/notion-crm-template', description: 'Tally -> Notion -> Gmail' },
    { id: 'custom-app', name: 'Custom App - Prompt to App', stack: 'dynamic', priceBase: 3000, githubTemplate: 'https://github.com/org/custom-blank', description: 'AI generates full app from prompt' },
    { id: 'prompt-pack', name: 'Prompt Engineering Pack', stack: 'notion, markdown', priceBase: 600, githubTemplate: 'https://github.com/org/prompt-pack-template', description: '50+ prompts, industry specific' }
  ]
};

// WhatsApp Cloud API
try {
  const { whatsappRouter } = require('./whatsapp');
  app.use('/api/whatsapp', whatsappRouter(db));
  console.log('[WhatsApp] Router mounted at /api/whatsapp/webhook');
} catch(e){ console.log('[WhatsApp] Router not loaded', e.message); }

// HEALTH
app.get('/api/health', (req,res)=>res.json({status:'ok', version:'v2-factory', time:new Date().toISOString(), blueprints: db.blueprints.length, clients: db.clients.length}));

// TEMPLATES / BLUEPRINTS
app.get('/api/blueprints', (req,res)=>res.json(db.blueprints));
app.get('/api/templates', (req,res)=>res.json(db.blueprints));

// 1. INTAKE+ Dynamic
app.post('/api/intake', (req,res)=>{
  const client = {
    id: Date.now().toString(),
    ...req.body,
    status: 'new',
    paymentStatus: 'unpaid',
    createdAt: new Date().toISOString(),
    source: req.body.source || 'tally',
    discoveryData: req.body.discoveryData || {},
    whiteLabel: { logo: '', color: '#ccff00', company: 'ITG' }
  };
  db.clients.push(client);
  console.log(`[Zapier] New client: ${client.name} | ${client.service} | ${client.source}`);
  const blueprint = db.blueprints.find(b=> b.name.toLowerCase().includes(client.service.toLowerCase().split(' ')[0]) ) || db.blueprints[0];
  res.json({ client, blueprint, zapierEvent: 'intake_received', next: 'builder' });
});
app.get('/api/clients', (req,res)=>res.json(db.clients));
app.get('/api/clients/:id', (req,res)=>{
  const c = db.clients.find(x=>x.id===req.params.id);
  if(!c) return res.status(404).json({error:'not found'});
  res.json(c);
});

// 2. AGENT DECISION
const { runAgentDecision } = require('./langchain-agent');
app.post('/api/agent/decide', async (req,res)=>{
  const { clientId } = req.body;
  const client = db.clients.find(c=>c.id===clientId);
  if(!client) return res.status(404).json({error:'client not found'});
  const blueprint = db.blueprints.find(b=> b.id===client.blueprintId) || db.blueprints.find(b=> client.service.toLowerCase().includes(b.id.split('-')[0])) || db.blueprints[2];

  const result = await runAgentDecision({ client, blueprint, discoveryData: client.discoveryData });
  res.json({ client: result.client, blueprint: result.blueprint, logs: result.logs });
});

// 3. PROPOSAL
const mdTemplate = `# Proposal for {{client_name}}
### {{company}} | Prepared by {{whiteLabelCompany}}

**Service:** {{service}} - {{blueprintName}}
**Date:** {{date}}
**Price:** {{price}}

## Discovery Summary
{{discovery}}

## Scope
{{scope}}

## Stack
{{stack}}

## Timeline: {{timeline}}

## Deliverables
- GitHub repo (private)
- Live URL on Render
- Prompt library + training docs
- Client portal access

---
*Auto-generated by ITG Flow Factory - LangChain + OpenRouter + Google Docs pipeline*
`;

app.post('/api/proposals/generate', (req,res)=>{
  const { clientId } = req.body;
  const client = db.clients.find(c=>c.id===clientId);
  if(!client) return res.status(404).json({error:'client not found'});
  const bp = db.blueprints.find(b=> b.id===client.blueprintId) || db.blueprints[0];
  const complexity = Object.keys(client.discoveryData||{}).length;
  const price = bp.priceBase + (complexity*150);
  let discovery = Object.entries(client.discoveryData||{}).map(([k,v])=> `- **${k}**: ${v}`).join('\n') || 'Standard intake';
  let md = mdTemplate.replaceAll('{{client_name}}', client.name)
    .replaceAll('{{company}}', client.company||'N/A')
    .replaceAll('{{whiteLabelCompany}}', client.whiteLabel?.company||'ITG')
    .replaceAll('{{service}}', client.service)
    .replaceAll('{{blueprintName}}', bp.name)
    .replaceAll('{{price}}', `$${price}`)
    .replaceAll('{{scope}}', bp.description)
    .replaceAll('{{stack}}', bp.stack)
    .replaceAll('{{discovery}}', discovery)
    .replaceAll('{{timeline}}', complexity>3?'2-3 weeks':'1 week')
    .replaceAll('{{date}}', new Date().toLocaleDateString());
  const prop = { id: Date.now().toString(), clientId, clientName: client.name, markdown: md, price, status:'sent', createdAt: new Date().toISOString() };
  db.proposals.push(prop);
  client.status='proposal_sent';
  res.json(prop);
});
app.get('/api/proposals', (req,res)=>res.json(db.proposals));
app.get('/api/proposals/:id/pdf', (req,res)=>{
  const prop = db.proposals.find(p=>p.id===req.params.id);
  if(!prop) return res.status(404).json({error:'proposal not found'});
  res.setHeader('Content-Type', 'text/markdown');
  res.setHeader('Content-Disposition', `attachment; filename="Proposal_${prop.clientName.replace(/\s+/g,'_')}.md"`);
  res.send(prop.markdown);
});

// 4. BUILDER STUDIO - SCAFFOLD
app.post('/api/builder/scaffold', async (req,res)=>{
  const { clientId, prompt, blueprintId } = req.body;
  const client = db.clients.find(c=>c.id===clientId);
  const bp = db.blueprints.find(b=>b.id===blueprintId) || db.blueprints[0];
  // Simulate file tree generation
  const files = [
    'app/page.tsx - Landing + auth',
    'app/api/agent/route.ts - LangChain agent',
    'lib/openrouter.ts - OpenRouter client',
    'components/ClientPortal.tsx',
    'supabase/schema.sql - DB',
    '.env.example',
    'README.md'
  ];
  if(bp.id==='whatsapp-bot') files.push('bot/index.js - Baileys handler', 'bot/flows.json');
  if(prompt?.toLowerCase().includes('real estate')) files.push('prompts/real-estate-50.md');

  const repo = {
    id: Date.now().toString(),
    clientId,
    blueprintId: bp.id,
    name: `${(client?.company||'client').toLowerCase().replace(/\s+/g,'-')}-${bp.id}-${Date.now().toString().slice(-4)}`,
    url: `https://github.com/itg-factory/${(client?.company||'client').toLowerCase()}-${bp.id}`,
    liveUrl: `https://${(client?.company||'client').toLowerCase().replace(/\s+/g,'-')}-${bp.id}.onrender.com`,
    files,
    prompt,
    status: 'deployed',
    createdAt: new Date().toISOString()
  };
  db.repos.push(repo);

  // Update delivery
  db.deliveries.push({ id: Date.now().toString(), clientId, stage:'build_started', note:`Scaffolded ${bp.name} from prompt: ${prompt?.slice(0,80)}`, at: new Date().toISOString(), repo });
  if(client) client.status='building';

  // If GitHub token present, would create real repo here
  if(process.env.GITHUB_TOKEN){
    console.log(`[GitHub] Would create repo ${repo.name} from template ${bp.githubTemplate}`);
  }
  if(process.env.RENDER_API_KEY){
    console.log(`[Render] Would deploy service ${repo.name}`);
  }

  res.json(repo);
});
app.get('/api/repos', (req,res)=>res.json(db.repos));

// 5. ONBOARDING
app.post('/api/onboarding/start', (req,res)=>{
  const { clientId } = req.body;
  const client = db.clients.find(c=>c.id===clientId);
  const checklist = [
    { id:'1', title:'Send welcome + portal link via WhatsApp/Gmail', done:false },
    { id:'2', title:'Create GitHub repo from blueprint', done:false },
    { id:'3', title:'Deploy to Render + env vars', done:false },
    { id:'4', title:'Setup Supabase DB', done:false },
    { id:'5', title:'Deliver prompt library', done:false }
  ];
  const onboarding = { clientId, clientName: client?.name, checklist, startedAt: new Date().toISOString() };
  db.tasks.push(onboarding);
  if(client) client.status='onboarding';
  res.json(onboarding);
});
app.get('/api/onboarding', (req,res)=>res.json(db.tasks));

// 6. DELIVERY
app.post('/api/delivery/update', (req,res)=>{
  const { clientId, stage, note } = req.body;
  const entry = { id: Date.now().toString(), clientId, stage, note, at: new Date().toISOString() };
  db.deliveries.push(entry);
  const client = db.clients.find(c=>c.id===clientId);
  if(client) client.status=stage;
  // Auto retainer
  if(stage==='delivered'){
    db.deliveries.push({ id: (Date.now()+1).toString(), clientId, stage:'retainer_scheduled', note:'Monthly optimization report scheduled (30 days)', at: new Date(Date.now()+30*24*60*60*1000).toISOString() });
  }
  res.json(entry);
});
app.get('/api/delivery', (req,res)=>res.json(db.deliveries));

// 7. PAYSTACK (SA friendly)
app.post('/api/paystack/initialize', (req,res)=>{
  const { clientId, amount } = req.body;
  // Mock Paystack init - replace with real Paystack API call
  const ref = `ITG_${Date.now()}`;
  const authUrl = `https://paystack.com/pay/${ref}`;
  console.log(`[Paystack] Init ${amount} for ${clientId} ref ${ref}`);
  res.json({ reference: ref, authorization_url: authUrl, amount, status:'pending' });
});
app.post('/api/paystack/webhook', (req,res)=>{
  // Paystack webhook - verify signature in production
  const { clientId } = req.body;
  const client = db.clients.find(c=>c.id===clientId);
  if(client){ client.paymentStatus='paid'; client.status='paid'; }
  console.log(`[Paystack] Payment confirmed for ${clientId}`);
  res.json({ ok:true });
});
app.post('/api/paystack/mock-confirm', (req,res)=>{
  const { clientId } = req.body;
  const client = db.clients.find(c=>c.id===clientId);
  if(client){ client.paymentStatus='paid'; client.status='paid'; }
  res.json({ ok:true, client });
});

// 8. FEEDBACK + PROMPT PACKS
app.post('/api/feedback', (req,res)=>{
  const { clientId, rating, feedback } = req.body;
  const t = {
    id: Date.now().toString(),
    clientId, rating, feedback,
    testimonial: rating>=4? feedback.slice(0,200): null,
    tags: ['ai','automation'],
    createdAt: new Date().toISOString()
  };
  db.testimonials.push(t);
  if(rating>=4){
    db.promptPacks.push({
      id: Date.now().toString(),
      title: `${db.clients.find(c=>c.id===clientId)?.service||'General'} - Winning Pack`,
      prompts: [feedback],
      industry: 'general',
      uses: 1,
      createdAt: new Date().toISOString()
    });
  }
  const client = db.clients.find(c=>c.id===clientId);
  if(client) client.status='completed';
  res.json(t);
});
app.get('/api/feedback', (req,res)=>res.json(db.testimonials));
app.get('/api/prompt-packs', (req,res)=>res.json(db.promptPacks));

// Serve frontend
const clientDist = path.join(__dirname, '../client/dist');
if(fs.existsSync(clientDist)){
  app.use(express.static(clientDist));
  app.get('*', (req,res)=>{
    if(req.path.startsWith('/api')) return res.status(404).json({error:'api not found'});
    res.sendFile(path.join(clientDist,'index.html'));
  });
}

app.listen(PORT,'0.0.0.0',()=>console.log(`ITG Factory v2 running on ${PORT}`));
